# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "c2dm-rails"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Heiko Moeller"]
  s.date = "2012-01-16"
  s.description = "c2dm-rails provides infrastructure to send push notifications to android devices via google c2dm."
  s.email = "femaref@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/models/c2dm/app.rb",
    "app/models/c2dm/base.rb",
    "app/models/c2dm/device.rb",
    "app/models/c2dm/notification.rb",
    "c2dm-rails.gemspec",
    "db/migrate/01_create_c2dm_apps.rb",
    "db/migrate/02_create_c2dm_devices.rb",
    "db/migrate/03_create_c2dm_notifications.rb",
    "lib/c2dm-rails.rb",
    "lib/connection.rb",
    "test/helper.rb"
  ]
  s.homepage = "https://github.com/Femaref/c2dm-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "c2dm-rails provides infrastructure to send push notifications to android devices via google c2dm."
  s.test_files = [
    "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<httparty>, ["> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
    else
      s.add_dependency(%q<rails>, ["~> 3.1.0"])
      s.add_dependency(%q<httparty>, ["> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.1.0"])
    s.add_dependency(%q<httparty>, ["> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
  end
end

